version: "3.8"

services:
  reverse-proxy:
    image: nginx:1.27.1
    container_name: tpa1_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - wnetwork
    depends_on:
      - cache
      - mariadb
    restart: unless-stopped

  app.tpa.local:
    image: nginx:1.27.1
    container_name: tpa1_app_nginx
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/public:/var/www/html
    networks:
      - wnetwork
    depends_on:
      - app-php-fpm
    restart: unless-stopped

  app-php-fpm:
    container_name: tpa1_app_php_fpm
    build:
      context: ./app
      dockerfile: php/Dockerfile
    volumes:
      - ./app/public:/var/www/html
      - ./app/public/vendor:/var/www/html/vendor
      - ./app/.env:/var/www/.env
    networks:
      - wnetwork
    restart: unless-stopped
    ports:
      - "5555:5555"

  cache:
    image: memcached:1.6.31
    container_name: tpa1_memcached
    ports:
      - "11211:11211"
    networks:
      - wnetwork

  mariadb:
    image: mariadb:11.6.1-ubi9-rc
    container_name: tpa1_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tpa_root_password
      MYSQL_DATABASE: tpa
      MYSQL_USER: tpa_user
      MYSQL_PASSWORD: tpa_user_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wnetwork

networks:
  wnetwork:
    driver: bridge

volumes:
  mariadb_data:
